name: System Health Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  health-check:
    name: Run Health Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./week-01/system_health.sh
        
      - name: Run System Health Script
        run: sudo bash ./week-01/system_health.sh

